events { worker_connections 1024; }

http {
    upstream flask_apps {
        server flask1:5000;
        server flask2:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://flask_apps;
        }
    }
}
